In [1]:
import requests

In [2]:
from bs4 import BeautifulSoup as bs

In [3]:
base_url="https://books.toscrape.com/catalogue/category/books_1/page-1.html"
response=requests.get(base_url)

print(response.text)

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    Books |
     Books to Scrape - Sandbox

</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:30" />
        <meta name="description" content="

" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="../../../static/oscar/favicon.ico" />






        <link rel="stylesheet" type="text/css" href="../../../static/oscar/css/styles.css" />

    <link rel="stylesheet" href="../../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" type="text/css" href="../../../static/oscar/css/datetimepicker.css" />












    </head>

    <body id="default" class="default">




    <header class="header container-fluid">
        <div class="page_inner">
            <div class="row">
                <div class="col-sm-8 h1"><a href="../../../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>


            </div>
        </div>
    </header>



<div class="container-fluid page">
    <div class="page_inner">

    <ul class="breadcrumb">
        <li>
            <a href="../../../index.html">Home</a>
        </li>

        <li class="active">Books</li>
    </ul>

        <div class="row">

            <aside class="sidebar col-sm-4 col-md-3">

                <div id="promotions_left">

                </div>




        <div class="side_categories">
            <ul class="nav nav-list">

                    <li>
                        <a href="index.html">

                                <strong>Books</strong>

                        </a>

                        <ul>


                    <li>
                        <a href="../books/travel_2/index.html">

                                Travel

                        </a>

                        </li>


                    <li>
                        <a href="../books/mystery_3/index.html">

                                Mystery

                        </a>

                        </li>


                    <li>
                        <a href="../books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/sequential-art_5/index.html">

                                Sequential Art

                        </a>

                        </li>


                    <li>
                        <a href="../books/classics_6/index.html">

                                Classics

                        </a>

                        </li>


                    <li>
                        <a href="../books/philosophy_7/index.html">

                                Philosophy

                        </a>

                        </li>


                    <li>
                        <a href="../books/romance_8/index.html">

                                Romance

                        </a>

                        </li>


                    <li>
                        <a href="../books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/fiction_10/index.html">

                                Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/childrens_11/index.html">

                                Childrens

                        </a>

                        </li>


                    <li>
                        <a href="../books/religion_12/index.html">

                                Religion

                        </a>

                        </li>


                    <li>
                        <a href="../books/nonfiction_13/index.html">

                                Nonfiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/music_14/index.html">

                                Music

                        </a>

                        </li>


                    <li>
                        <a href="../books/default_15/index.html">

                                Default

                        </a>

                        </li>


                    <li>
                        <a href="../books/science-fiction_16/index.html">

                                Science Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>

                        </li>


                    <li>
                        <a href="../books/add-a-comment_18/index.html">

                                Add a comment

                        </a>

                        </li>


                    <li>
                        <a href="../books/fantasy_19/index.html">

                                Fantasy

                        </a>

                        </li>


                    <li>
                        <a href="../books/new-adult_20/index.html">

                                New Adult

                        </a>

                        </li>


                    <li>
                        <a href="../books/young-adult_21/index.html">

                                Young Adult

                        </a>

                        </li>


                    <li>
                        <a href="../books/science_22/index.html">

                                Science

                        </a>

                        </li>


                    <li>
                        <a href="../books/poetry_23/index.html">

                                Poetry

                        </a>

                        </li>


                    <li>
                        <a href="../books/paranormal_24/index.html">

                                Paranormal

                        </a>

                        </li>


                    <li>
                        <a href="../books/art_25/index.html">

                                Art

                        </a>

                        </li>


                    <li>
                        <a href="../books/psychology_26/index.html">

                                Psychology

                        </a>

                        </li>


                    <li>
                        <a href="../books/autobiography_27/index.html">

                                Autobiography

                        </a>

                        </li>


                    <li>
                        <a href="../books/parenting_28/index.html">

                                Parenting

                        </a>

                        </li>


                    <li>
                        <a href="../books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/humor_30/index.html">

                                Humor

                        </a>

                        </li>


                    <li>
                        <a href="../books/horror_31/index.html">

                                Horror

                        </a>

                        </li>


                    <li>
                        <a href="../books/history_32/index.html">

                                History

                        </a>

                        </li>


                    <li>
                        <a href="../books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>

                        </li>


                    <li>
                        <a href="../books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>

                        </li>


                    <li>
                        <a href="../books/business_35/index.html">

                                Business

                        </a>

                        </li>


                    <li>
                        <a href="../books/biography_36/index.html">

                                Biography

                        </a>

                        </li>


                    <li>
                        <a href="../books/thriller_37/index.html">

                                Thriller

                        </a>

                        </li>


                    <li>
                        <a href="../books/contemporary_38/index.html">

                                Contemporary

                        </a>

                        </li>


                    <li>
                        <a href="../books/spirituality_39/index.html">

                                Spirituality

                        </a>

                        </li>


                    <li>
                        <a href="../books/academic_40/index.html">

                                Academic

                        </a>

                        </li>


                    <li>
                        <a href="../books/self-help_41/index.html">

                                Self Help

                        </a>

                        </li>


                    <li>
                        <a href="../books/historical_42/index.html">

                                Historical

                        </a>

                        </li>


                    <li>
                        <a href="../books/christian_43/index.html">

                                Christian

                        </a>

                        </li>


                    <li>
                        <a href="../books/suspense_44/index.html">

                                Suspense

                        </a>

                        </li>


                    <li>
                        <a href="../books/short-stories_45/index.html">

                                Short Stories

                        </a>

                        </li>


                    <li>
                        <a href="../books/novels_46/index.html">

                                Novels

                        </a>

                        </li>


                    <li>
                        <a href="../books/health_47/index.html">

                                Health

                        </a>

                        </li>


                    <li>
                        <a href="../books/politics_48/index.html">

                                Politics

                        </a>

                        </li>


                    <li>
                        <a href="../books/cultural_49/index.html">

                                Cultural

                        </a>

                        </li>


                    <li>
                        <a href="../books/erotica_50/index.html">

                                Erotica

                        </a>

                        </li>


                    <li>
                        <a href="../books/crime_51/index.html">

                                Crime

                        </a>

                        </li>

                            </ul></li>


            </ul>
        </div>



            </aside>

            <div class="col-sm-8 col-md-9">

                <div class="page-header action">
                    <h1>Books</h1>
                </div>






<div id="messages">

</div>


                <div id="promotions">

                </div>




    <form method="get" class="form-horizontal">

        <div style="display:none">


        </div>




                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>

        <section>
            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>

            <div>
                <ol class="row">

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../a-light-in-the-attic_1000/index.html"><img src="../../../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg" alt="A Light in the Attic" class="thumbnail"></a>


            </div>




                <p class="star-rating Three">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£51.77</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../tipping-the-velvet_999/index.html"><img src="../../../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg" alt="Tipping the Velvet" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>



            <div class="product_price">








        <p class="price_color">Â£53.74</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../soumission_998/index.html"><img src="../../../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg" alt="Soumission" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../soumission_998/index.html" title="Soumission">Soumission</a></h3>



            <div class="product_price">








        <p class="price_color">Â£50.10</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../sharp-objects_997/index.html"><img src="../../../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg" alt="Sharp Objects" class="thumbnail"></a>


            </div>




                <p class="star-rating Four">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>



            <div class="product_price">








        <p class="price_color">Â£47.82</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../sapiens-a-brief-history-of-humankind_996/index.html"><img src="../../../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg" alt="Sapiens: A Brief History of Humankind" class="thumbnail"></a>


            </div>




                <p class="star-rating Five">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£54.23</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="../../the-requiem-red_995/index.html"><img src="../../../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg" alt="The Requiem Red" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="../../the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>



            <div class="product_price">








        <p class="price_color">Â£22.65</p>


<p class="instock availability">

In [4]:
soup=bs(response.text,"html.parser")
# soup

print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   Books |
     Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:30" name="created"/>
  <meta content="

" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="../../../static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="../../../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="../../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="../../../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="../../../index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="../../../index.html">
       Home
      </a>
     </li>
     <li class="active">
      Books
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="index.html">
          <strong>
           Books
          </strong>
         </a>
         <ul>
          <li>
           <a href="../books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="../books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="../books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="../books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="../books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="../books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="../books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="../books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="../books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="../books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="../books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="../books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="../books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="../books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="../books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="../books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="../books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="../books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="../books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="../books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="../books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="../books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="../books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="../books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="../books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="../books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="../books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="../books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="../books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="../books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="../books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="../books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="../books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="../books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="../books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="../books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="../books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="../books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="../books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="../books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="../books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="../books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="../books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="../books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="../books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="../books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="../books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="../books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="../books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="../books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        Books
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="../../../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="../../../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="../../../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="../../../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../../../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="../../../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../../../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="../../the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../../../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="../../the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">
             The Coming Woman: A ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">

In [5]:
raw_books=[]
articles=soup.find_all("article", class_="product_pod")
# articles
len(articles)

20

# name of book

In [6]:
count=0
for book in articles:
    name=book.h3.a
    # count+=1
    # print(count)
    print(name)

<a href="../../a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a>
<a href="../../tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a>
<a href="../../soumission_998/index.html" title="Soumission">Soumission</a>
<a href="../../sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a>
<a href="../../sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a>
<a href="../../the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a>
<a href="../../the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a>
<a href="../../the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a>
<a href="../../the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a>
<a href="../../the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a>
<a href="../../starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a>
<a href="../../shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a>
<a href="../../set-me-free_988/index.html" title="Set Me Free">Set Me Free</a>
<a href="../../scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a>
<a href="../../rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a>
<a href="../../our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a>
<a href="../../olio_984/index.html" title="Olio">Olio</a>
<a href="../../mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a>
<a href="../../libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a>
<a href="../../its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a>

# all code for practicing

In [7]:
from urllib.parse import urljoin

In [ ]:
current_page=1
raw_books=[]
url=base_url
while url and current_page < 4:
    response=requests.get(url)
    soup=bs(response.text,"html.parser")
    articles=soup.find_all("article", class_="product_pod")
    len(articles)

    for book in articles:
        name=book.h3.a["title"]
        # price=book.find("p", class_="price_color")
        price=book.find("p", class_="price_color").text
        rating=book.find("p",class_="star-rating")["class"][1]

        img_src=book.find("img")["src"]
        img_url=urljoin(base_url,img_src)
        img_content=requests.get(img_url).content
        img_name=name.replace(":","")+".png"
        img_path=f"../raw_images/{img_name}"
        with open(img_path,"wb") as img_file:
            img_file.write(img_content)



        raw_books.append(
            {
                "name":name,
                "price":price,
                "rating":rating,
                "image_path":img_path
            }
        )

    next_btn=soup.find("li",class_="next")
    current_page+=1
    url=f"https://books.toscrape.com/catalogue/category/books_1/page-{current_page}.html" if next_btn else None

# save raw data

In [20]:
import pandas as pd
df=pd.DataFrame(raw_books)
df.to_csv("raw_data_of_books.csv")

# clean raw data

In [60]:
df=pd.read_csv("raw_data_of_books.csv")
df.head()

,Unnamed: 0,name,price,rating,image_path
0,0,A Light in the Attic,Â£51.77,Three,../raw_images/A Light in the Attic.png
1,1,Tipping the Velvet,Â£53.74,One,../raw_images/Tipping the Velvet.png
2,2,Soumission,Â£50.10,One,../raw_images/Soumission.png
3,3,Sharp Objects,Â£47.82,Four,../raw_images/Sharp Objects.png
4,4,Sapiens: A Brief History of Humankind,Â£54.23,Five,../raw_images/Sapiens A Brief History of Human...

In [61]:
def clean_data(df):
    df["price"] = df["price"].str.replace(r"[^\d.]", "", regex=True).astype(float)
    df["name"]=df["name"].astype("string")
    df["image_path"]=df["image_path"].astype("string")

    rating_map={
        "One":1,
        "Two":2,
        "Three":3,
        "Four":4,
        "Five":5
    }
    df["rating"]=df["rating"].map(rating_map)
    return df

In [62]:
clean_data(df).head()

,Unnamed: 0,name,price,rating,image_path
0,0,A Light in the Attic,51.77,3,../raw_images/A Light in the Attic.png
1,1,Tipping the Velvet,53.74,1,../raw_images/Tipping the Velvet.png
2,2,Soumission,50.10,1,../raw_images/Soumission.png
3,3,Sharp Objects,47.82,4,../raw_images/Sharp Objects.png
4,4,Sapiens: A Brief History of Humankind,54.23,5,../raw_images/Sapiens A Brief History of Human...

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        60 non-null     string
 1   price       60 non-null     float64
 2   rating      60 non-null     int64
 3   image_path  60 non-null     string
dtypes: float64(1), int64(1), string(2)
memory usage: 2.0 KB

In [75]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [77]:
df.to_csv("cleaned_data_of_books.csv" ,index=False)

# organizer

In [79]:
import os
import shutil

def organize_images_by_rating(df):
    base_folder = "images_by_rating"

    for i in range(1, 6):
        folder_path = os.path.join(base_folder, f"{i}_stars")
        os.makedirs(folder_path, exist_ok=True)

    for _, row in df.iterrows():
        image_path = row["image_path"]
        rating = row["rating"]

        if image_path and os.path.exists(image_path):
            file_name = os.path.basename(image_path)

            destination = os.path.join(
                base_folder,
                f"{rating}_stars",
                file_name
            )

            try:
                shutil.move(image_path, destination)
            except:
                print(f"Error moving {file_name}")

In [ ]:
organize_images_by_rating(df)

In [78]:
import os

base_folder = "ratings_data"

for i in range(1, 6):
    folder_path = os.path.join(base_folder, f"{i}_stars")
    os.makedirs(folder_path, exist_ok=True)

    df_rating = df[df["rating"] == i]
    
    file_path = os.path.join(folder_path, "data.csv")
    df_rating.to_csv(file_path, index=False)